### ISSUE TITLE
cfn_to_yaml.rb doesn't process Conditions section

### ISSUE THREAD

**Issue by rjamestaylor** [evanwieren/cfn_mason#2]
Just a note that valid CFN templates may have a Conditions section and cfn_to_yaml.rb currently doesn't process this section, thus resulting in a loss of information from CFN to YAML. 

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html

**Comment by rjamestaylor** [comment]
I submitted a pull request to add Conditions section support. 

However, this raises another issue: cfn_to_yaml.rb has an explicit "DSL" -- named CFN sections. If Amazon adds new sections, this utility will currently not report an error/warning and result in lossy translations from JSON to YAML.

**Comment by evanwieren** [comment]
This has been complete.
